In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('breast-cancer-wisconsin.data',names=[
'Sample_code_number',
'Clump_Thickness',
'Uniformity_of_Cell_Size',
'Uniformity_of_Cell_Shape',
'Marginal_Adhesion',
'Single_Epithelial_Cell_Size',
'Bare_Nuclei',
'Bland_Chromatin',
'Normal_Nucleoli',
'Mitoses',
'Class'
])

In [3]:
data.head()

Sample_code_number  Clump_Thickness  Uniformity_of_Cell_Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity_of_Cell_Shape  Marginal_Adhesion  Single_Epithelial_Cell_Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare_Nuclei  Bland_Chromatin  Normal_Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [4]:
data.dtypes

Sample_code_number              int64
Clump_Thickness                 int64
Uniformity_of_Cell_Size         int64
Uniformity_of_Cell_Shape        int64
Marginal_Adhesion               int64
Single_Epithelial_Cell_Size     int64
Bare_Nuclei                    object
Bland_Chromatin                 int64
Normal_Nucleoli                 int64
Mitoses                         int64
Class                           int64
dtype: object

In [5]:
data

Sample_code_number  Clump_Thickness  Uniformity_of_Cell_Size  \
0               1000025                5                        1   
1               1002945                5                        4   
2               1015425                3                        1   
3               1016277                6                        8   
4               1017023                4                        1   
..                  ...              ...                      ...   
694              776715                3                        1   
695              841769                2                        1   
696              888820                5                       10   
697              897471                4                        8   
698              897471                4                        8   

     Uniformity_of_Cell_Shape  Marginal_Adhesion  Single_Epithelial_Cell_Size  \
0                           1                  1                            2   
1                           4                  5                            7   
2                           1                  1                            2   
3                           8                  1                            3   
4                           1                  3                            2   
..                        ...                ...                          ...   
694                         1                  1                            3   
695                         1                  1                            2   
696                        10                  3                            7   
697                         6                  4                            3   
698                         8                  5                            4   

    Bare_Nuclei  Bland_Chromatin  Normal_Nucleoli  Mitoses  Class  
0             1                3                1        1      2  
1            10                3                2        1      2  
2             2                3                1        1      2  
3             4                3                7        1      2  
4             1                3                1        1      2  
..          ...              ...              ...      ...    ...  
694           2                1                1        1      2  
695           1                1                1        1      2  
696           3                8               10        2      4  
697           4               10                6        1      4  
698           5               10                4        1      4  

[699 rows x 11 columns]

In [ ]:
def is_non_numeric(x):
    return not x.isnumeric()

In [ ]:
mask=data['Bare_Nuclei'].apply(is_non_numeric)

In [ ]:
mask

In [ ]:
data_nm=data[~mask]
print(data_nm)

In [ ]:
data_nm.head()

In [6]:
from sklearn.impute import KNNImputer #imputation

In [7]:
df=pd.DataFrame(data)

In [8]:
imputer=KNNImputer(n_neighbors=2)

In [9]:
import numpy as np
dataf=df.replace({'?':np.nan})

In [10]:
df_filled = imputer.fit_transform(dataf)

In [11]:
df_filled.shape

(699, 11)

In [12]:
xx=dataf
for i in xx:
    if i== '?':
        print(i)
    else:
        print('no')

no
no
no
no
no
no
no
no
no
no
no


In [13]:
xx=df_filled
for i in xx:
    if i== 'nan':
        print(i)
    else:
        print('no')

no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
n

C:\Users\aneri\anaconda3\envs\deeplearning\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  This is separate from the ipykernel package so we can avoid doing imports until


In [14]:
df_filled=df_filled.astype('int64')

In [15]:
type(df_filled)

numpy.ndarray

In [16]:
data_input=np.delete(df_filled,(0,10),axis=1)
data_input

array([[ 5,  1,  1, ...,  3,  1,  1],
       [ 5,  4,  4, ...,  3,  2,  1],
       [ 3,  1,  1, ...,  3,  1,  1],
       ...,
       [ 5, 10, 10, ...,  8, 10,  2],
       [ 4,  8,  6, ..., 10,  6,  1],
       [ 4,  8,  8, ..., 10,  4,  1]], dtype=int64)

In [21]:
data_output=df_filled[:,10]
data_output

array([2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 4, 4,
       2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4, 2, 4, 4, 4,
       4, 2, 4, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4,
       2, 4, 4, 2, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4,
       2, 4, 4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2, 2,
       4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 4, 2,
       2, 4, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4,
       2, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2,
       2, 4, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4, 2, 4, 2, 2, 4, 4, 4, 4, 2, 2,
       2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 4, 2, 2, 2, 2, 4, 4, 4, 4,
       4, 2, 4, 4, 4, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 4, 4,
       4, 2, 4, 4, 2, 2, 4, 4, 2, 4, 2, 2, 2, 4, 4,

In [22]:
np.unique(data_output)

array([2, 4], dtype=int64)

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data_input,data_output,test_size=0.2,random_state=1)
x_train,x_val,y_train,y_val=train_test_split(x_train,y_train,test_size=0.2,random_state=1)

In [25]:
x_train.shape

(447, 9)

In [26]:
x_val.shape

(112, 9)

In [27]:
x_test.shape

(140, 9)

In [28]:
from sklearn.tree import DecisionTreeClassifier

In [29]:
model_1=  DecisionTreeClassifier(max_depth=3)

In [30]:
model_1.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=3)

In [31]:
from sklearn.metrics import accuracy_score

In [32]:
y_pred_train=model_1.predict(x_train)

In [33]:
y_pred_val=model_1.predict(x_val)

In [34]:
print(accuracy_score(y_train,y_pred_train))

0.970917225950783


In [35]:
print(accuracy_score(y_val,y_pred_val))

0.9375


In [36]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

In [37]:
tree_para={'criterion':['gini','entropy'],'max_depth':[5,10,15,20,25,40,50,60,100]}
clf=GridSearchCV(DecisionTreeClassifier(),tree_para,cv=5)
clf.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [5, 10, 15, 20, 25, 40, 50, 60, 100]})

In [38]:
clf.best_params_

{'criterion': 'entropy', 'max_depth': 5}

In [39]:
model=  DecisionTreeClassifier(criterion='entropy',max_depth=5)

In [40]:
model.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [41]:
y_pred_train=model.predict(x_train)
y_pred_val=model.predict(x_val)

In [42]:
print(accuracy_score(y_train,y_pred_train))

0.9798657718120806


In [43]:
print(accuracy_score(y_val,y_pred_val))

0.9375


In [44]:
y_pred_test=model.predict(x_test)

In [45]:
print(accuracy_score(y_test,y_pred_test))

0.9357142857142857


In [46]:
import pickle


In [47]:
with open('save-model.pickle','wb') as f:
    pickle.dump(model,f)